### ISSUE TITLE
Make it EU-wide

### ISSUE THREAD

**Issue by pcav** [warrieka/inspireNL#2]
I do not know how feasible is this, but it would be interesting if the same structure could be used for other countries as well.

**Comment by warrieka** [comment]
I use several parts that are geonetwork specific. As long  other country's are using geonetwork, It should be easy to port.  The EU INSPIRE portal uses a custom solr based solution, that would require starting from scratch: http://inspire-geoportal.ec.europa.eu/solr/select?q=belgium

**Comment by pvgenuchten** [comment]
would be interesting to add a configuration option in about-screen that allows to modify the geonetwork url (or select from a list of predefined known hosts) in stead of hardcoding it in metadatParser.py (note that you can already test it locally by installing the plugin and modifying that file in the plugin folder)

Also consider that the metasearch plugin offers you similar functionality to any csw endpoint

**Comment by warrieka** [comment]
That should be possible indeed.

**Comment by warrieka** [comment]
Give that the plugin is now purely CSW based this should be simple. Someone should fork this and make new version.
