### ISSUE TITLE
Migrate to geonetwork 3.2

### ISSUE THREAD

**Issue by pvgenuchten** [warrieka/inspireNL#4]
in  geonetwork 3.2 a new api is introduced (already in 3.0 some of the api-calls changed, making the plugin fail). What are your thoughts on making the plugin more robust against several versions of the geonetwork product

via the xml.info service the plugin could detect which version of geonetwork is installed and then decide to use the according api.

One of the design principles of the new API is to prevent this situation in future, the API's will get a version number so any major change on the API will result in a new API version number, with option to keep the previous API active

**Comment by warrieka** [comment]
Yes I feared this might happen, but my employer really wanted those dropdown listboxes.

I would prefer to use  the CSW instead, actually, but i I din't manage to figure out how to get those keyword-lists.

Maybe I should look into it these days.

**Comment by pvgenuchten** [comment]
In that case the plugin could work against any CSW. But then it would be good to align your developments with the metasearch plugin.

Getting a list of contributing organisations or keywords from a thesaurus is not a feature of CSW2, the [getdomain](http://docs.opengeospatial.org/is/12-168r6/12-168r6.html#35) operation of cat3 may in future solve this... Individual catalog products will probably all have an implementation for that, which in the end could leave you with code like: switch (type) {case "geonetworkv2" ... case "geonetworkv3" ... case pyCSWv1 ...}
