### ISSUE TITLE
problem installing plugin with Qgis 3.4.3

### ISSUE THREAD

**Issue by PeterDorsman** [warrieka/inspireNL#5]
I tried to install de Plugin from the Plugin Library as mentioned in the manual, but was not able to find it.
So in stead i downloaded version 2.3 from Github and tried to install it. When installing and activating the plugin, it came up with an error: "Can't find methode classFactory". See below below for the complete errorcode

I hope you can fix this. If you need more information, please let me know.

-----------------------------------------------------------------------------------------
Kon plug-in 'inspireNL' niet laden wegens een fout bij het aanroepen van de methode classFactory() 

ModuleNotFoundError: No module named 'inspireNL.dataCatalog' 
Traceback (most recent call last):
  File "c:/OSGeo4w/apps/qgis/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/113176/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inspireNL\__init__.py", line 9, in classFactory
    from .inspireNL import inspireNL
  File "c:/OSGeo4w/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/113176/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\inspireNL\inspireNL.py", line 8, in 
    from .dataCatalog import dataCatalog
  File "c:/OSGeo4w/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'inspireNL.dataCatalog'

Python versie: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS versie: 3.4.3-Madeira Madeira, 2f64a3c4e7 

Python pad:
c:/OSGeo4w/apps/qgis/./python
C:/Users/113176/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/113176/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
c:/OSGeo4w/apps/qgis/./python/plugins
C:\OSGeo4w\bin\python37.zip
c:\OSGeo4w\apps\Python37\DLLs
c:\OSGeo4w\apps\Python37\lib
C:\OSGeo4w\bin
c:\OSGeo4w\apps\Python37
c:\OSGeo4w\apps\Python37\lib\site-packages
C:/Users/113176/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by thijsbrentjens** [comment]
I have the same issue with the plugin from the release. I think it is related to missing (python) files in the release itself. If I download a zip-file with all the code from git and install from that zip file, the plugin is installed and runs. It does not seem the preferred way of installation I guess, so a new release including the missing python files would be nice.

**Comment by PeterDorsman** [comment]
@thijsbrentjens Bedankt voor de tip. Op deze manier was het inderdaad eenvoudig om de plugin werkend te krijgen

**Comment by warrieka** [comment]
I have updated this release with new version of the zip-package, this works fine under windows/qgis3.4: https://github.com/warrieka/inspireNL/releases/download/2.3/inspireNL.zip 

The plugin has not been released yet, so it is indeed not yet available on the plugin-repo. 
I also fixed some spelling errors in the documentation.
